import Layout from "@/components/Layout";
import Head from "next/head";
import ProfilePic from "../../public/images/profile/developer-pic-1.png";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow, ContactIcon } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/profile/developer-pic-1.png";
import Contact from "@/components/Contact";
export default function Home() {
  const scrollToQuestionNode = (id) => {
    const element = document.getElementById(id);
    element.scrollIntoView({ block: "end", behavior: "smooth" });
  };

  return (
    <>
      <Head>
        <title>Portfolio SK</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light scroll-smooth">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={ProfilePic}
                alt="CodeBucks"
                className="w-full h-auto"
                priority //this is used for priority so it will disabled the lazyloading so it appear immedieately
                sizes="(max-width: 768px) 100vw,(max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design"
                className="!text-6xl text-left"
              />
              <p className="my-4 text-base font-medium">
                As a skilled frontend and full-stack developer (MERN), I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js, Next js and
                web development
              </p>
              <div className="flex gap-2 items-center self-start mt-2 ">
                <Link
                  href="/dummy.pdf"
                  target="_black"
                  download={true}
                  className="flex items-center bg-dark text-light  hover:bg-light hover:text-dark p-2.5 px-6 rounded-lg text-lg font-semibold border-2 border-solid border-transparent dark:bg-light/90 dark:text-dark hover:dark:bg-dark hover:dark:text-light   hover:border-dark hover:dark:border-light  "
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <span
                  onClick={() => scrollToQuestionNode("contact")}
                  className="flex items-center bg-green-900 text-light  hover:bg-light hover:text-dark p-2.5 px-6 rounded-lg text-lg font-semibold border-2 border-solid border-transparent  dark:text-light hover:dark:bg-dark hover:dark:text-light   hover:border-dark hover:dark:border-light cursor-pointer  "
                >
                  Contact
                  <ContactIcon className={"w-6 ml-1"} />
                </span>
              </div>
            </div>
          </div>
        </Layout>{" "}
        {/* <HireMe /> */}
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={lightBulb} alt="CodeBucks" className="w-full  h-auto" />
        </div>
      </main>
      <Contact />
    </>
  );
}
